const NOT_FOUND = 404
const LENGTH_REQUIRED = 411
const OK = 200
const CREATED = 201
const UNAUTHORIZED = 401
const INTERNAL_SERVER = 500

module.exports = {
  NOT_FOUND,
  LENGTH_REQUIRED,
  OK,
  CREATED,
  UNAUTHORIZED,
  INTERNAL_SERVER
}